# Generated by Django 5.1.5 on 2025-02-03 03:17

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('TimeKeeping_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timerecord',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
